### ISSUE TITLE
Migrate release pipeline to Github Actions

### ISSUE THREAD

**Issue by ldruschk** [enowars/enochecker_core#11]

**Comment by Trolldemorted** [comment]
The release pipeline is on gh actions, do you want to switch to the github package registry?

**Comment by ldruschk** [comment]
Not the release pipeline, that's still here: https://github.com/enowars/enochecker_core/blob/master/azure-pipelines-release.yml

**Comment by Trolldemorted** [comment]
ah oh I am blind, sorry^^

**Comment by ldruschk** [comment]
closed by https://github.com/enowars/enochecker_core/commit/17902cb26289f3fe93d810ee63ba48ca1e9d185a
