### ISSUE TITLE
Sane Defaults for Development

### ISSUE THREAD

**Issue by domenukk** [enowars/enochecker_core#15]
As checker authors constantly interact with the checker during development, all values should have sane dev defaults for non-optional keys.
This makes interaction with the checker easy and comes at no obvious drawback.

For reference, the current defaults in the pre-core checkerlib are:
```python
# The json spec a checker request follows.
spec: List[Union[Required, Optional]] = [
    Required("method", CHECKER_METHODS),  # method to execute
    Required("address", str),  # address to check
    Optional("runId", int, 0),  # internal ID of this run inside our db
    Optional("teamName", str, "FakeTeam"),  # the team name
    Optional("teamId", int, 1),  # team ID
    Optional("roundId", int, 0),  # which tick we are in
    Optional("relatedRoundId", int, 0),  # Flag-Related
    Optional("roundLength", int, 300000),  # the default tick time
    Optional("flag", str, "ENOTESTFLAG"),  # the flag or noise to drop or get
    Optional("flagIndex", int, 0),
    Optional("timeout", int, 30000),  # timeout we have for this run
]
```

**Comment by domenukk** [comment]
If we think it's necessary to adhere to the spec for non-dev use, using the defaults could be optional and enabled on a `/dev` route only.
The enochecker-cli can also import the defaults from `enochecker_core`

**Comment by domenukk** [comment]
For reference, the current cli defaults are here:
https://github.com/enowars/enochecker_cli/blob/f0605828688ac25c2cfdc4be1c0f51ccedcb4abf/enochecker_cli/base.py#L19

**Comment by ldruschk** [comment]
See my comment in https://github.com/enowars/enochecker_cli/issues/8, in my opinion this issue is obsolete
